FROM openjdk:17
EXPOSE 8080
COPY target/ordering-pilotes-container-0.0.1-SNAPSHOT.jar /app/ordering-pilotes-container-0.0.1-SNAPSHOT.jar
WORKDIR /app
CMD ["java", "-jar", "ordering-pilotes-container-0.0.1-SNAPSHOT.jar"]